language: android
sudo: false
android:
  components:
  - platform-tools
  - tools
  - build-tools-27.0.3
  - android-27
  - sys-img-armeabi-v7a-android-26
  - extra-android-support
  - extra-android-m2repository
env:
  global:
  - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"
